services:
  alertwechat:
    image: alertwechat:latest
    container_name: alertwechat
    restart: always
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app

networks:
  xizhao:
    external: true
